name: Chrome

on:
  push:
    branches:
      - master
    paths:
      - 'CookieClicker.Ui.Tests/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: docker build --no-cache -f "./CookieClicker.dockerfile" -t cc-tests ..

      - name: Start Selenium Grid
        run: docker run --rm -d -p 4444:4444 -p 7900:7900 --shm-size 2g selenium/standalone-chrome:dev

      - name: Run tests
        run: docker run --network host -e WebDriver=remote -e Test_Browser=chrome cc-tests
